##Each new term in the Fibonacci sequence is generated by adding the previous
##two terms. By starting with 1 and 2, the first 10 terms will be:
##1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##Find the sum of all the even-valued terms in the sequence which do not exceed
##four million.

def f1(limit):
    Fib=[1,2]
    while Fib[-2]+Fib[-1]<limit:
        Fib.append(Fib[-2]+Fib[-1])
    return sum(filter(lambda x:x%2==0,Fib))
def f2(limit):
    B=[2,8]
    while B[-2]+4*B[-1]<limit:
        B.append(B[-2]+4*B[-1])
    return sum(B)
print(f2(4000000))

